states <- function() c("Alabama",
                       "Alaska",
                       "Arizona",
                       "Arkansas",
                       "California",
                       "Colorado",
                       "Connecticut",
                       "Delaware",
                       "Florida",
                       "Georgia",
                       "Hawaii",
                       "Idaho",
                       "Illinois",
                       "Indiana",
                       "Iowa",
                       "Kansas",
                       "Kentucky",
                       "Louisiana",
                       "Maine",
                       "Maryland",
                       "Massachusetts",
                       "Michigan",
                       "Minnesota",
                       "Mississippi",
                       "Missouri",
                       "Montana",
                       "Nebraska",
                       "Nevada",
                       "New Hampshire",
                       "New Jersey",
                       "New Mexico",
                       "New York",
                       "North Carolina",
                       "North Dakota",
                       "Ohio",
                       "Oklahoma",
                       "Oregon",
                       "Pennsylvania",
                       "Rhode Island",
                       "South Carolina",
                       "South Dakota",
                       "Tennessee",
                       "Texas",
                       "Utah",
                       "Vermont",
                       "Virginia",
                       "Washington",
                       "West Virginia",
                       "Wisconsin",
                       "Wyoming")

states_and_dc <- function() {
  c(states(), "District of Columbia")
} 

electoral_delegates <- list("Alabama" = 9,
                            "Alaska" = 3,
                            "Arizona" = 11,
                            "Arkansas" = 6,
                            "California" = 55,
                            "Colorado" = 9,
                            "Connecticut" = 7,
                            "Delaware" = 3,
                            "District of Columbia" = 3,
                            "Florida" = 29,
                            "Georgia" = 16,
                            "Hawaii" = 4,
                            "Idaho" = 4,
                            "Illinois" = 20,
                            "Indiana" = 11,
                            "Iowa" = 6,
                            "Kansas" = 6,
                            "Kentucky" = 8,
                            "Louisiana" = 8,
                            "Maine" = 4,
                            "Maryland" = 10,
                            "Massachusetts" = 11,
                            "Michigan" = 16,
                            "Minnesota" = 10,
                            "Mississippi" = 6,
                            "Missouri" = 10,
                            "Montana" = 3,
                            "Nebraska" = 5,
                            "Nevada" = 6,
                            "New Hampshire" = 4,
                            "New Jersey" = 14,
                            "New Mexico" = 5,
                            "New York" = 29,
                            "North Carolina" = 15,
                            "North Dakota" = 3,
                            "Ohio" = 18,
                            "Oklahoma" = 7,
                            "Oregon" = 7,
                            "Pennsylvania" = 20,
                            "Rhode Island" = 4,
                            "South Carolina" = 9,
                            "South Dakota" = 3,
                            "Tennessee" = 11,
                            "Texas" = 38,
                            "Utah" = 6,
                            "Vermont" = 3,
                            "Virginia" = 13,
                            "Washington" = 12,
                            "West Virginia" = 5,
                            "Wisconsin" = 10,
                            "Wyoming" = 3)

electoral_delegates.abbrev <- list("AL" = 9,
  "AK" = 3,
  "AZ" = 11,
  "AR" = 6,
  "CA" = 55,
  "CO" = 9,
  "CT" = 7,
  "DE" = 3,
  "DC" = 3,
  "FL" = 29,
  "GA" = 16,
  "HI" = 4,
  "ID" = 4,
  "IL" = 20,
  "IN" = 11,
  "IA" = 6,
  "KS" = 6,
  "KY" = 8,
  "LA" = 8,
  "ME" = 4,
  "MD" = 10,
  "MA" = 11,
  "MI" = 16,
  "MN" = 10,
  "MS" = 6,
  "MO" = 10,
  "MT" = 3,
  "NE" = 5,
  "NV" = 6,
  "NH" = 4,
  "NJ" = 14,
  "NM" = 5,
  "NY" = 29,
  "NC" = 15,
  "ND" = 3,
  "OH" = 18,
  "OK" = 7,
  "OR" = 7,
  "PA" = 20,
  "RI" = 4,
  "SC" = 9,
  "SD" = 3,
  "TN" = 11,
  "TX" = 38,
  "UT" = 6,
  "VT" = 3,
  "VA" = 13,
  "WA" = 12,
  "WV" = 5,
  "WI" = 10,
  "WY" = 3)

is.state <- function(s) {
  s %in% states()
}

is.dc <- function(s) {
  s %in% c("DC", "D.C.", "District of Columbia")
}

has.electoral_delegates <- function(s) {
  is.state(s) || is.dc(s)
}

neighboring_states <- list(
  "Alabama" = c("Florida", "Georgia", "Mississippi", "Tennessee"),
  "Alaska" = c(),
  "Arizona" = c("California", "Colorado", "Nevada", "New Mexico", "Utah"),
  "Arkansas" = c("Louisiana", "Mississippi", "Missouri", "Oklahoma", "Tennessee", "Texas"),
  "California" = c("Arizona", "Nevada", "Oregon"),
  "Colorado" = c("Arizona", "Kansas", "Nebraska", "New Mexico", "Oklahoma", "Utah", "Wyoming"),
  "Connecticut" = c("Massachusetts", "New York", "Rhode Island"),
  "Delaware" = c("Maryland", "New Jersey", "Pennsylvania"),
  "District of Columbia" = c("Maryland", "Virginia"),
  "Florida" = c("Alabama", "Georgia"),
  "Georgia" = c("Alabama", "Florida", "North Carolina", "South Carolina", "Tennessee"),
  "Hawaii" = c(),
  "Idaho" = c("Montana", "Nevada", "Oregon", "Utah", "Washington", "Wyoming"),
  "Illinois" = c("Indiana", "Iowa", "Michigan", "Kentucky", "Missouri", "Wisconsin"),
  "Indiana" = c("Illinois", "Kentucky", "Michigan", "Ohio"),
  "Iowa" = c("Illinois", "Minnesota", "Missouri", "Nebraska", "South Dakota", "Wisconsin"),
  "Kansas" = c("Colorado", "Missouri", "Nebraska", "Oklahoma"),
  "Kentucky" = c("Illinois", "Indiana", "Missouri", "Ohio", "Tennessee", "Virginia", "West Virginia"),
  "Louisiana" = c("Arkansas", "Mississippi", "Texas"),
  "Maine" = c("New Hampshire"),
  "Maryland" = c("Delaware", "District of Columbia", "Pennsylvania", "Virginia", "West Virginia"),
  "Massachusetts" = c("Connecticut", "New Hampshire", "New York", "Rhode Island", "Vermont"),
  "Michigan" = c("Illinois", "Indiana", "Minnesota", "Ohio", "Wisconsin"),
  "Minnesota" = c("Iowa", "Michigan", "North Dakota", "South Dakota", "Wisconsin"),
  "Mississippi" = c("Alabama", "Arkansas", "Louisiana", "Tennessee"),
  "Missouri" = c("Arkansas", "Illinois", "Iowa", "Kansas", "Kentucky", "Nebraska", "Oklahoma", "Tennessee"),
  "Montana" = c("Idaho", "North Dakota", "South Dakota", "Wyoming"),
  "Nebraska" = c("Colorado", "Iowa", "Kansas", "Missouri", "South Dakota", "Wyoming"),
  "Nevada" = c("Arizona", "California", "Idaho", "Oregon", "Utah"),
  "New Hampshire" = c("Maine", "Massachusetts", "Vermont"),
  "New Jersey" = c("Delaware", "New York", "Pennsylvania"),
  "New Mexico" = c("Arizona", "Colorado", "Oklahoma", "Texas", "Utah"),
  "New York" = c("Connecticut", "Massachusetts", "New Jersey", "Pennsylvania", "Rhode Island", "Vermont"),
  "North Carolina" = c("Georgia", "South Carolina", "Tennessee", "Virginia"),
  "North Dakota" = c("Minnesota", "Montana", "South Dakota"),
  "Ohio" = c("Indiana", "Kentucky", "Michigan", "Pennsylvania", "West Virginia"),
  "Oklahoma" = c("Arkansas", "Colorado", "Kansas", "Missouri", "New Mexico", "Texas"),
  "Oregon" = c("California", "Idaho", "Nevada", "Washington"),
  "Pennsylvania" = c("Delaware", "Maryland", "New Jersey", "New York", "Ohio", "West Virginia"),
  "Rhode Island" = c("Connecticut", "Massachusetts", "New York"),
  "South Carolina" = c("Georgia", "North Carolina"),
  "South Dakota" = c("Iowa", "Minnesota", "Montana", "Nebraska", "North Dakota", "Wyoming"),
  "Tennessee" = c("Alabama", "Arkansas", "Georgia", "Kentucky", "Mississippi", "Missouri", "North Carolina", "Virginia"),
  "Texas" = c("Arkansas", "Louisiana", "New Mexico", "Oklahoma"),
  "Utah" = c("Arizona", "Colorado", "Idaho", "Nevada", "New Mexico", "Wyoming"),
  "Vermont" = c("Massachusetts", "New Hampshire", "New York"),
  "Virginia" = c("District of Columbia", "Kentucky", "Maryland", "North Carolina", "Tennessee", "West Virginia"),
  "Washington" = c("Idaho", "Oregon"),
  "West Virginia" = c("Kentucky", "Maryland", "Ohio", "Pennsylvania", "Virginia"),
  "Wisconsin" = c("Illinois", "Iowa", "Michigan", "Minnesota"),
  "Wyoming" = c("Colorado", "Idaho", "Montana", "Nebraska", "South Dakota", "Utah")
)