states <- function() c("Alabama",
                       "Alaska",
                       "Arizona",
                       "Arkansas",
                       "California",
                       "Colorado",
                       "Connecticut",
                       "Delaware",
                       "Florida",
                       "Georgia",
                       "Hawaii",
                       "Idaho",
                       "Illinois",
                       "Indiana",
                       "Iowa",
                       "Kansas",
                       "Kentucky",
                       "Louisiana",
                       "Maine",
                       "Maryland",
                       "Massachusetts",
                       "Michigan",
                       "Minnesota",
                       "Mississippi",
                       "Missouri",
                       "Montana",
                       "Nebraska",
                       "Nevada",
                       "New Hampshire",
                       "New Jersey",
                       "New Mexico",
                       "New York",
                       "North Carolina",
                       "North Dakota",
                       "Ohio",
                       "Oklahoma",
                       "Oregon",
                       "Pennsylvania",
                       "Rhode Island",
                       "South Carolina",
                       "South Dakota",
                       "Tennessee",
                       "Texas",
                       "Utah",
                       "Vermont",
                       "Virginia",
                       "Washington",
                       "West Virginia",
                       "Wisconsin",
                       "Wyoming")

states_and_dc <- function() {
  c(states(), "District of Columbia")
}

electoral_delegates <- list("Alabama" = 9,
                            "Alaska" = 3,
                            "Arizona" = 11,
                            "Arkansas" = 6,
                            "California" = 55,
                            "Colorado" = 9,
                            "Connecticut" = 7,
                            "Delaware" = 3,
                            "District of Columbia" = 3,
                            "Florida" = 29,
                            "Georgia" = 16,
                            "Hawaii" = 4,
                            "Idaho" = 4,
                            "Illinois" = 20,
                            "Indiana" = 11,
                            "Iowa" = 6,
                            "Kansas" = 6,
                            "Kentucky" = 8,
                            "Louisiana" = 8,
                            "Maine" = 4,
                            "Maryland" = 10,
                            "Massachusetts" = 11,
                            "Michigan" = 16,
                            "Minnesota" = 10,
                            "Mississippi" = 6,
                            "Missouri" = 10,
                            "Montana" = 3,
                            "Nebraska" = 5,
                            "Nevada" = 6,
                            "New Hampshire" = 4,
                            "New Jersey" = 14,
                            "New Mexico" = 5,
                            "New York" = 29,
                            "North Carolina" = 15,
                            "North Dakota" = 3,
                            "Ohio" = 18,
                            "Oklahoma" = 7,
                            "Oregon" = 7,
                            "Pennsylvania" = 20,
                            "Rhode Island" = 4,
                            "South Carolina" = 9,
                            "South Dakota" = 3,
                            "Tennessee" = 11,
                            "Texas" = 38,
                            "Utah" = 6,
                            "Vermont" = 3,
                            "Virginia" = 13,
                            "Washington" = 12,
                            "West Virginia" = 5,
                            "Wisconsin" = 10,
                            "Wyoming" = 3)

is.state <- function(s) {
  s %in% states()
}

is.dc <- function(s) {
  s %in% c("DC", "D.C.", "District of Columbia")
}

has.electoral_delegates <- function(s) {
  is.state(s) || is.dc(s)
}